<a href="https://colab.research.google.com/github/Sanim27/Torch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
print(torch.rand(2,2))

tensor([[0.8732, 0.7518],
        [0.3075, 0.9302]])


In [4]:
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [5]:
x[0][0]=100
print(x)

tensor([[100,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]])


In [6]:
y=torch.zeros(2,2)

In [7]:
print(y)

tensor([[0., 0.],
        [0., 0.]])


In [8]:
z=torch.ones(1,2)+torch.ones(1,2)

In [9]:
z

tensor([[2., 2.]])

######For rank 1 matrix we can use item() to get the data item

In [10]:
print(torch.rand(1).item())

0.5598490238189697


In [11]:
cpu_tensor=torch.rand(2)

In [13]:
cpu_tensor.device

device(type='cpu')

In [14]:
gpu_tensor=cpu_tensor.to('cuda')
gpu_tensor.device

device(type='cuda', index=0)

We can use max() function to get the maximum in tensor and like before use item() function for rank 1 matrix thus obtained.

In [2]:
x_max=torch.rand(2,2).max()
x_max.item()

0.6568174958229065

Changing tensor from long tensor to a float tensor

In [4]:
long_tensor=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(long_tensor.type())

torch.LongTensor


In [6]:
float_tensor=long_tensor.to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

In [7]:
float_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [8]:
long_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
random_tensor=torch.rand(2,2)
print(random_tensor)
random_log=random_tensor.log2()
print(random_log)

tensor([[0.4581, 0.4939],
        [0.9413, 0.2974]])
tensor([[-1.1262, -1.0178],
        [-0.0873, -1.7496]])


Here, in the code above, when log2() is done, an intermediate temporary tensor is made to store the result

In [10]:
random_tensor=torch.rand(2,2)
print(random_tensor)
random_log=random_tensor.log2_()
print(random_log)

tensor([[0.4647, 0.4370],
        [0.9000, 0.4223]])
tensor([[-1.1056, -1.1942],
        [-0.1520, -1.2437]])


Here, in the code above, since log2_() is used , hence there is no intermediate tensor that stores the result. This is inplace function

MNIST handwritten dataset is of size 784, Hence it has to be converted to (1,28,28). This requires reshaping. This reshaping is done by **view()** or **reshape()**

In [16]:
flat_tensor=torch.rand(784)
# print(flat_tensor)
print(flat_tensor.shape)

# using view()
reshaped_tensor=flat_tensor.view(1,28,28)
# print(reshaped_tensor)
print(reshaped_tensor.shape)

#using reshape()
reshaped_tensor1=flat_tensor.reshape(1,28,28)
# print(reshaped_tensor1)
print(reshaped_tensor1.shape)

torch.Size([784])
torch.Size([1, 28, 28])
torch.Size([1, 28, 28])


## So what is the difference between view() and reshape() ?

### view(): Can throw an error if the memory isn’t contiguous. Changes to the original tensor affect the view.


###reshape(): More reliable as it handles non-contiguous memory automatically. Changes to the original tensor may or may not affect the reshaped tensor (depends if a new tensor is created).

## Better to use reshape() for error-less working

# ----------------------------------------------------------------------------

# Rearranging dimensions of tensors ...

Most images are in the shape ( height, width, channels ) . But in pytorch we would want them as ( channels, height, width).

### We can use permute() for this purpose.

In [17]:
hwc_tensors=torch.rand(640,480,3)
chw_tensors=hwc_tensors.permute(2,0,1)
print(hwc_tensors.shape)
print(chw_tensors.shape)

torch.Size([640, 480, 3])
torch.Size([3, 640, 480])


# Tensor broadcasting

### burrowed from numpy, tensor broadcasting helps in performing operations between a tensor and a small tensor. You can broadcast two tensors, if starting backward from their trailing dimensions:
1. The two dimensions are equal.
2. One of the dimensions is 1.

In [19]:
# Tensor A of shape (3, 1)
A = torch.tensor([[1], [2], [3]])

# Tensor B of shape (1, 4)
B = torch.tensor([[10, 20, 30, 40]])

# Broadcasting will happen here
C = A + B

print("Tensor A shape:", A.shape)
print("Tensor B shape:", B.shape)
print("Result Tensor C shape:", C.shape)
print("Result Tensor C:\n", C)

Tensor A shape: torch.Size([3, 1])
Tensor B shape: torch.Size([1, 4])
Result Tensor C shape: torch.Size([3, 4])
Result Tensor C:
 tensor([[11, 21, 31, 41],
        [12, 22, 32, 42],
        [13, 23, 33, 43]])


In [20]:
# Tensor D of shape (2, 3)
D = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Tensor E of shape (4,)
E = torch.tensor([10, 20, 30, 40])

# This will throw an error due to incompatible shapes
try:
    F = D + E
except RuntimeError as e:
    print("Error:", e)

Error: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1


In [21]:
# Tensor G of shape (2, 1)
G = torch.tensor([[1], [2]])

# Tensor H of shape (2, 3)
H = torch.tensor([[10, 20, 30], [40, 50, 60]])

# Broadcasting will happen
I = G * H

print("Tensor G shape:", G.shape)
print("Tensor H shape:", H.shape)
print("Result Tensor I shape:", I.shape)
print("Result Tensor I:\n", I)


Tensor G shape: torch.Size([2, 1])
Tensor H shape: torch.Size([2, 3])
Result Tensor I shape: torch.Size([2, 3])
Result Tensor I:
 tensor([[ 10,  20,  30],
        [ 80, 100, 120]])
